pipeline {
    agent any
    
    environment {
        // Project paths
        TOOLCHAIN_FILE = 'tools/toolchain.cmake'
        BUILD_DIR = 'build'
    }
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    
    stages {
        stage('Environment Setup') {
            steps {
                sh '''
                    # Create build directory
                    mkdir -p ${BUILD_DIR}
                '''
            }
        }
        
        stage('CMake Configure') {
            steps {
                sh '''
                    cd ${BUILD_DIR}
                    cmake .. -DCMAKE_TOOLCHAIN_FILE=../${TOOLCHAIN_FILE}
                '''
            }
        }
        
        stage('Build Bootloader') {
            steps {
                sh '''
                    cd ${BUILD_DIR}
                    make bootloader_bs.elf
                '''
            }
        }
        
        stage('Build Floats') {
            steps {
                sh '''
                    cd ${BUILD_DIR}
                    make floats_bs.elf
                '''
            }
        }
        
        stage('Build Linux App') {
            steps {
                sh '''
                    cd ${BUILD_DIR}
                    make pc_app_linux
                '''
            }
        }
        
       // stage('Build Windows App') {
       //     steps {
       //         sh '''
       //             cd ${BUILD_DIR}
       //             make pc_app_windows
       //         '''
       //     }
       // }
        
        stage('Archive Artifacts') {
            steps {
                dir(BUILD_DIR) {
                    archiveArtifacts artifacts: '''
                        bootloader/bootloader_bs.elf,
                        application/floats_bs.elf,
			dist/DigitalFloatsControl,
                    ''', fingerprint: true
                }
            }
        }
    }
    
    post {
        always {
            cleanWs(cleanWhenNotBuilt: false,
                   deleteDirs: true,
                   disableDeferredWipeout: true,
                   notFailBuild: true,
                   patterns: [[pattern: 'build/', type: 'INCLUDE']])
        }
        
    }
}
